# Generated by Django 5.2.8 on 2025-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviewatched',
            name='isUse',
            field=models.BooleanField(default=False),
        ),
    ]
