# Generated by Django 5.2.8 on 2025-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_favouritemovies_thedegreeofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritemovies',
            name='isUse',
            field=models.BooleanField(default=False),
        ),
    ]
